### ISSUE TITLE
slow loading pages

### ISSUE THREAD

**Issue by mekeke79** [n1k0/casperjs#1131]
It is normal that Casperjs with phantomjs (1.9.2) load page more slowly than curl or file_get_contents in php?

**Comment by jr-duboc** [comment]
This might be because CasperJS loads all the CSS+JavaScript included and in your page, so that it can evaluate it and do everything CasperJS does: screenshots, events, filling forms, etc.
A quick search on Google tells me that curl or file_get_contents in PHP don't do that (see http://stackoverflow.com/questions/8508723/curl-or-file-get-contents-for-downloading-whole-webpage-with-css-images-and-js, maybe that will help).
That said, I could be completely wrong about this, so maybe someone with more experience can confirm or show me what I've done wrong...

**Comment by mickaelandrieu** [comment]
yes, it's normal. curl or all-based scrapper can't interpret or execute javascript.
In fact, casperjs don't scrap websites but realy execute it through phantomjs in a real browser engine (webkit, the old engine of google chrome).
