### ISSUE TITLE
Can't open xx/bootstrap.js - Windows

### ISSUE THREAD

**Issue by mattalberon** [n1k0/casperjs#1271]
I have the following error message on $ casperjs:

"Can't open 'filepath/casperjs/bin/bootstrap.js"

I have phantomjs 1.9.8 and Python 2.7.10 installed, on Windows 7. I am running the current version of casperjs. All paths are up to date.

What do you think is going wrong?

**Comment by cvillanujr** [comment]
Same issue here. Any idea how to fix this? Thanks.

**Comment by hxhxd** [comment]
@cvillanujr  

```shell
Pierre@Pierre-PC ~
$ cd /cygdrive/d/casperjs/bin/

Pierre@Pierre-PC /cygdrive/d/casperjs/bin
$ ls
bootstrap.js  casperjs  casperjs.exe  usage.txt

Pierre@Pierre-PC /cygdrive/d/casperjs/bin
$ ln -sf `pwd`/casperjs.exe /usr/local/bin/casperjs

Pierre@Pierre-PC /cygdrive/d/casperjs/bin
$ casperjs --version
Can't open '/cygdrive/d/casperjs/bin/bootstrap.js'
```

I'm trying to get casperjs working on cygwin, but got no luck yet. 
Under cmd it works but not inside cygwin shell.
I've tried git clone then ln -sf, same error always.

**Comment by istr** [comment]
Please elaborate on your reasons to try using casper through cygwin?

There is native windows support by means of the mono builds, so I fear that there won't be any support for cygwin based setups in the near future (because manpower is really restricted in this project right now).

**Comment by mepard** [comment]
Try forcing it to use casperjs.exe instead of casperjs. Link casperjs.exe instead of casperjs, or if you add casperjs/bin to the search path, rename or remove casperjs.

**Comment by hxhxd** [comment]
@istr 
I was trying to use casperjs under shell, will use it within shell script later.
Since shell does't have the tricky character escape problem cmd has.
I was using the pre-built exes, I'm wondering why that error happened in cygwin.
I would like to compile another one in cygwin so long as it works in both cmd and cygwin.

Anyway, it's a great tool, thanks a lot :)

ps, after many failed tries, I deleted the pre-built one, installed phantomjs and casperjs via npm, it seems ok now.
Only one side effect, Pardon,  I don't know how to describe this,
···shell
 Pierre@Pierre-PC /cygdrive/c/Users/Pierre
$ casperjs --version

Pierre@Pierre-PC /cygdrive/c/Users/Pierre
$ 1.1.0-beta5


Pierre@Pierre-PC /cygdrive/c/Users/Pierre
$ phantomjs --version
2.1.1
```
