### ISSUE TITLE
Click doesn't work for Twitter's follower follow / unfollow button in CasperJS environment, from the follower's page 

### ISSUE THREAD

**Issue by Siona-A** [n1k0/casperjs#1334]
Hi everyone,
I actually want to follow / unfollow Twitter accounts in a CasperJS environment. I am used to do some testing with a navigator (for example with Firefox or Chrome) before I write my JavaScript code. I have tried several button click syntaxes that just work great in the navigator, but not in the CasperJS environment.

For example, I log in to Twitter with Firefox, and go to this URL "https://twitter.com/googledrive" (it is an account that I am already following). I move the mouse over the "Follow / Unfollow" button and right click in order to inspect the button element. The navigator opens a console (just like F12). 
Then I right click on the element (in the HTML code) and select "Copy Unique Selector". 

Then I just have to write the following line in the Console bar :
document.querySelector("span.button-text:nth-child(3)").click();

Or even this one works
document.querySelector(".button-text.unfollow-text").click();

And when I go back to my followings list, the Google Drive account has been removed.
CasperJS part :
I would like to do the same action in CasperJS environment. I am able to log in, go to the page containing the account I am following, click on the Google Drive account, and when I try to do the unfollowing click, CasperJS throws no error, and do the click action. But when I go to Firefox and refresh my page, I still have the same number of followings... My full code is right below ::

var casper = require("casper").create({
    verbose: true,
    logLevel: 'debug',
    pageSettings: { userAgent: "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" }
});

var email = 'My Email';
var auth = 'My Password';

casper.start('https://twitter.com/', function() {
    this.fill('form.t1-form.signin', {
        "session[username_or_email]" : email,
        "session[password]" : auth
    },true);
}); //It leads me to my Twitter Dashboard

//Go to my followings list
casper.then(function(){
    console.log(this.getTitle());
    this.click("div.ProfileCardStats:nth-child(3) > ul:nth-child(1) > li:nth-child(2) > a:nth-child(1)");
    casper.wait(2000);
});

//I click one of the links to Google Drive page
casper.then(function(){
    console.log(this.getTitle());
    this.click("#stream-item-user-32468665 > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > span:nth-child(2) > a:nth-child(1)");
    casper.wait(2000);
});

//Unfollow action
casper.then(function(){
    console.log(this.getTitle());
    this.click("button.user-actions-follow-button");
    casper.wait(2000);
});

casper.then(function(){
    casper.wait(1000, function(){
        this.back();
    });
    casper.wait(2000);
});

//Then I want to go back to my followings list
casper.then(function(){
    casper.wait(2000, function(){
        console.log(this.getTitle());
    });
});

casper.run();

The debugging says that the click is done, but in fact not really.
I even tried with casperJS evaluate function, in order to use jQuery, but it still doesn't do the click action : this.evaluate(function(){ 
     $('span.button-text:nth-child(3)').click(); 
}); 

And the following didn't work either, but I get in the condition and I get the message "Button detected". this.mouse.move("button.user-actions-follow-button:nth-child(2)"); 
if(this.exists("button.user-actions-follow-button:nth-child(2) > span:nth-child(3)")){ 
     casper.click("button.user-actions-follow-button.js-follow-btn.follow-button.bt‌​n:hover"); 
     console.log("Button detected");
}

What am I doing wrong? If I could at least understand why this code doesn't work, or get to know if it is an impossible action to do, it would help me a lot.

Thank you, 

Siona-A

**Comment by bitwombat** [comment]
I often have this problem a lot when using Casper, and I'll point you to this important note in the docs:

    Warning

    Step functions added to then() are processed in two different cases:

        when the previous step function has been executed,
        when the previous main HTTP request has been executed and the page loaded;

    Note that there’s no single definition of page loaded; is it when the DOMReady event
    has been triggered? Is it “all requests being finished”? Is it *all application logic being
    performed”? Or “all elements being rendered”? The answer always depends on the
    context. Hence why you’re encouraged to always use the waitFor() family methods to
    keep explicit control on what you actually expect.

So what I think that means is that you're executing click() when the DOM's not ready yet, so the event is happening on nothing.  Restructure your code to use the waitFor() functions to make sure things are there when you go to click them.

**Comment by istr** [comment]
This kind of discussion belongs to [the mailing list](https://groups.google.com/forum/#!forum/casperjs).

**Comment by bitwombat** [comment]
Hi @istr.  I've contributed my answer to a [similar thread](https://groups.google.com/forum/#!topic/casperjs/_XiqQ3ejNvY) on the mailing list, if anybody wants to pile into the discussion, but I think this is actually a CasperJS documentation issue.  

While there's a strong warning in the [documentation on .then](http://docs.casperjs.org/en/latest/modules/casper.html#then), many examples use .then as if you can write sequential web-page manipulating CasperJS scripts.

As the warning states, this won't really work.  Many mailing list questions are from people being tripped up by this same thing - Calling .click() in a .then(), and having it fail silently because the DOM isn't ready.

Is there a technical fix?  Maybe .then() waiting for one of the three conditions listed in the warning (DOM ready, all requests fulfilled, or all elements rendered)?  What are the trade-offs?  Execution time?  Causing other problems?

Either way, I got tripped up by this myself as a newbie, so I'm wondering if something in the documentation or examples should emphasize this more heavily.  Something blunt like: "Manipulate pages with event-driven code using the WaitFor() family, rather than sequentially using .then()".  This is basically what the warning in .then says, but it apparently needs to be more prominent.

As for the examples, ".then()" is used in the [FAQ]() and even the [docs for .click()](http://docs.casperjs.org/en/latest/modules/casper.html#click) but not WaitFor.  WaitFor doesn't show up in the FAQ, nor the [quickstart](http://docs.casperjs.org/en/latest/quickstart.html).  

This is probably where everybody is getting the idea that .click should work the way they're trying to use it.
