### ISSUE TITLE
CasperJS: execution time with slimerjs is significantly lower than with PhantomJS

### ISSUE THREAD

**Issue by mandeepm91** [n1k0/casperjs#1340]
I have written an automated web scraping process which navigates to a series of 5 pages and scrapes the required information.

I tried running the script using SlimerJS to make the debugging easy. The execution time of the entire process was less than 15 seconds. I tried multiple times with same results.

Then I tried running it with PhantomJS. Surprisingly, the execution time increased significantly. It was over 35 seconds every time.

I was hoping PhantomJS to be much faster since there is no opening of any GUI. How can I debug why its taking much longer in PhantomJS?

If I am not able to make it faster in PhantomJS, is it advisable to use SlimerJS in production server with headless setup ?

I am running this on Ubuntu 14.04 machine

**Comment by istr** [comment]
This is strange because usually slimerjs tends to be slower than phantomjs. On my Ubuntu 14.04 machine:

Using engine slimerjs

```bash
ENGINE_FLAGS="--local-to-remote-url-access=yes --ignore-ssl-errors=yes" ENGINE_EXECUTABLE=~/bin/slimerjs CASPER_ENGINE=slimerjs /usr/bin/time -v xvfb-run make selftest
```

output
```
Command being timed: "xvfb-run make selftest"
	User time (seconds): 15.19
	System time (seconds): 0.73
	Percent of CPU this job got: 45%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:35.04
```

Using latest phantomjs engine:

```bash
ENGINE_FLAGS="--local-to-remote-url-access=yes --ignore-ssl-errors=yes" ENGINE_EXECUTABLE=~/bin/phantomjs-2.0.1 /usr/bin/time -v make selftest
```

output
```
Command being timed: "make selftest"
	User time (seconds): 4.67
	System time (seconds): 0.64
	Percent of CPU this job got: 24%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:21.65
```

Please note that [there is a mailing list](https://groups.google.com/forum/#!forum/casperjs) where you should ask for support with your own scripts and try to isolate the problem passing your script (or relevant parts thereof) directly to the engines. See [CONTRIBUTING.md](https://github.com/n1k0/casperjs/blob/master/CONTRIBUTING.md).
