### ISSUE TITLE
Bad URL after fill & submit form

### ISSUE THREAD

**Issue by darkterra** [n1k0/casperjs#1363]
Hello everyone,

I am new in using Capser.JS (1.1.0-beta3), according to the documentation, I can fill out a form and send it automatically.

But...

After sending instead of arriving on my URL + "form_comp.php" as demonstrated on the following tag :
`<form name=" f1" id="f1" action=" form_comp.php " method="post" >`

I arrive with the following URL:
`/form.php/form_comp.php`

I do not understand why Casper.JS adds the content of the tag action to the current URL ?

Have you any suggestions?

**Comment by istr** [comment]
This is a very basic question about [relative URLs](http://www.w3.org/TR/WD-html40-970917/htmlweb.html#htmlurl). 

From what you describe I would guess that your "```my URL```" from where you submit your form is ```.../form.php/``` instead of ```.../form.php```. If the current URL is the former, the behavior is correct and will be the same in any other browser. If it is the latter, then, in fact, this is a bug, but in the underlying engine you use (which I can hardly imagine, though).

Please ask on [the mailing list](http://groups.google.com/group/casperjs) first, to see if your problem is in any way related to CasperJS, before filing issues against CasperJS. Thanks.

**Comment by darkterra** [comment]
Ok , thank you for your quick response @istr , it works.
