### ISSUE TITLE
nodeModulePath in bootstrap.js hangs when CasperJS is run from /

### ISSUE THREAD

**Issue by daniele-rapagnani** [n1k0/casperjs#1479]
If you run CasperJS from the filesystem root on linux it hangs indefinitely.
The problem seems to be caused by the nodeModulePath function in bootstrap.js going in an infinite loop, but I don't know why as I haven't investigated further.

This happens in casperjs-1.1.0-beta5 with PhantomJS 2.1.1 (but I suspect the issue is unrelated to the PhantomJS version).

**Comment by jefleponot** [comment]
Yes, I saw that since a while.
I had fix it quickly
I was waiting until someone complains about this problem ... before proposing a PR :smile: 

jef

**Comment by jefleponot** [comment]
a temp workaround : you have  to comment  line 291 
// nodeModulePath(path) ||

**Comment by jefleponot** [comment]
explanation : 

in bootstrap.js file, "cli" module is called before the "phantom.casperScriptBaseDir" variable is initialized 

````
408    phantom.casperArgs = require('cli').parse(phantomArgs);
409
410    if (true === phantom.casperArgs.get('cli')) {
411        initCasperCli(phantom.casperArgs);
412    }
````

And in the "cli.js" file, a require to "system" is done So a loop is created in the code of bootstrap

````
278            do {
279                resolved = resolveFile(path, fs.pathJoin(baseDir, 'node_modules'));
280                prevBaseDir = baseDir;
281                baseDir = fs.absolute(fs.pathJoin(prevBaseDir, '..'));
282            } while (!resolved && baseDir !== '/' && baseDir !== prevBaseDir);
````

because of a bug in fs.absolute :
- on linux  absolute ("/..") =  "/"
- on phantomJS : absolute("/..") = "/.."
- on slimerJS : absolute("/..") = ""

there is different way to solve this bug, you can just change order in cli.js of system module call.

**Comment by jefleponot** [comment]
Hi @daniele-rapagnani 

Can you test my PR #1483 ?
Do you know if trouble occurs on windows too ?

**Comment by dogrocker** [comment]
Hello, 
I think, I'd the same problem but with Docker container on (casperjs-1.1.0-beta5 with PhantomJS 2.1.1).

**Comment by istr** [comment]
I guess we'll merge @jefleponot s PR #1483 shortly.

**Comment by mickaelandrieu** [comment]
@dogrocker fix merged again master branch.

Closed :)
