### ISSUE TITLE
Update colorizer.js to check for ANSICON

### ISSUE THREAD

**Issue by renatodarrigo** [n1k0/casperjs#490]
Using ANSICON (https://github.com/adoxa/ansicon) we can have colors on Windows' CMD or PowerShell.

ANSICON sets the env variable 'ANSICON' so checking for it might do the job.

**Comment by Namek** [comment]
bump. Is there any progress about it?

**Comment by Namek** [comment]
Hmm, well, actually it worked. After fixing my paths I just needed to run `ansicon` instead of `cmd` to see colors in console. Tested with CasperJS 1.1.0-beta3 and PhantomJS 2.0.0

**Comment by Namek** [comment]
Another note: colorizer doesn't work with `ansicon` and SlimerJS (v0.9.6). It doesn't work in that way CasperJS prints escape characters but somehow ansicon doesn't get it. Result: even more ugliness visible in the console.

**Comment by istr** [comment]
This should be in place at least since 1.1.0-beta1, see [the commit that updates the documentation](https://github.com/n1k0/casperjs/commit/ded41ef4cc38d18697fd570b035d2ce390e07eff) and [the commit that implements it](https://github.com/n1k0/casperjs/commit/0e147d3d2af6c0aec72e9dc14896cc66a707ddcf).

@Namek please file a separate slimerjs specific issue if the problem with slimerjs persists with current master. Thanks.
