### ISSUE TITLE
Fix random failures on Travis

### ISSUE THREAD

**Issue by n1k0** [n1k0/casperjs#537]
This [changeset](https://github.com/n1k0/casperjs/commit/64ead008ed4f7051a769a210100fd8b0dbfbaad5) has resulted in a [broken build](https://travis-ci.org/n1k0/casperjs/jobs/9097572) for no obvious reason as it was only documentation related, so I think we're facing random failures here.

**Comment by asimd** [comment]
Any feedback with this one, we're forced to move our tests to inactive test folder since Travis CI is giving us random failures all the time?

**Comment by istr** [comment]
@asimd Could you please point us to your failing test suite? There is at least one known issue with popups that invariably creates intermittent errors when travis is under high load. The problem here is that we know *what* fails but not yet how to replicate it under controlled conditions nor how to fix it.

**Comment by istr** [comment]
I am closing this. We have some identified sources of random failures that are fixed now, a [rather long streak of passing builds](https://travis-ci.org/n1k0/casperjs/builds) and know the reason for recent build failures (bitbucket throttling).

Feel free to re-open if this hits again in a random manner.
