### ISSUE TITLE
CasperJS is not compatible with underscore bind (_.bind)

### ISSUE THREAD

**Issue by PixelsCommander** [n1k0/casperjs#773]
CasperJS is not compatible with underscore bind (_.bind). It does not work with this.

Any thoughts on this?

It works with loadash or prototype.bind, however it is not an option to switch to loadash only because of testing platform.

**Comment by istr** [comment]
Please re-open if you could verify this against current master, because the ```Function.bind``` shim to support older PhantomJS versions was replaced recently: https://github.com/n1k0/casperjs/pull/1404

If you still have the issue, please attach a minimal test case and state the PhantomJS version and platform that lead to the problem.

Thank you.
